import { readdir } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';

/**
 * bun build --compile produces one portable executable with no external files
 * next to it - reading apps/web/dist from the filesystem at runtime only works
 * in dev, not once compiled (the binary can run from any working directory).
 * So instead we inline every built frontend file as a base64 string literal
 * here; Bun embeds those bytes directly into the compiled binary, and
 * index.ts serves them from memory instead of disk.
 *
 * Files are inlined as base64 strings rather than `with { type: "arraybuffer" }`
 * imports because Bun's bundler applies extension-based loaders (HTML, JS) to
 * imported files regardless of the import attribute, which fails on already-hashed,
 * already-built asset paths (it tries to re-resolve their internal references).
 * Base64 string literals sidestep that entirely, at the cost of ~33% size overhead
 * on the (small) dashboard bundle.
 */

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.json': 'application/json',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
};

const distDir = join(import.meta.dir, '../../web/dist');
const outFile = join(import.meta.dir, '../src/webAssets.generated.ts');

async function collectFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(full)));
    } else {
      files.push(full);
    }
  }
  return files;
}

async function main() {
  let files: string[];
  try {
    files = await collectFiles(distDir);
  } catch {
    files = [];
  }

  if (files.length === 0) {
    await Bun.write(
      outFile,
      `// Auto-generated by scripts/generate-web-assets.ts - run \`bun run web:build\` first.\n` +
        `export const webAssets: Record<string, { content: Uint8Array; contentType: string }> = {};\n`,
    );
    console.log('[generate-web-assets] no dashboard build found - wrote empty manifest');
    return;
  }

  const entries: string[] = [];

  for (const file of files) {
    const urlPath = '/' + relative(distDir, file).split('\\').join('/');
    const contentType = MIME_TYPES[extname(file)] ?? 'application/octet-stream';
    const base64 = Buffer.from(await Bun.file(file).arrayBuffer()).toString('base64');
    entries.push(
      `  ${JSON.stringify(urlPath)}: { content: Uint8Array.from(atob(${JSON.stringify(base64)}), (c) => c.charCodeAt(0)), contentType: ${JSON.stringify(contentType)} },`,
    );
  }

  const output =
    `// Auto-generated by scripts/generate-web-assets.ts - do not edit by hand.\n` +
    `export const webAssets: Record<string, { content: Uint8Array; contentType: string }> = {\n${entries.join('\n')}\n};\n`;

  await Bun.write(outFile, output);
  console.log(`[generate-web-assets] embedded ${files.length} dashboard files`);
}

main();
